# Generated by Django 2.0.9 on 2018-12-06 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('run', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=40)),
                ('cuidad', models.CharField(max_length=30)),
                ('comuna', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ordendetrabajo',
            fields=[
                ('id_orden', models.AutoField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('hora_ini', models.DateTimeField()),
                ('hora_term', models.DateTimeField()),
                ('id_ascensor', models.IntegerField()),
                ('modelo_ascensor', models.CharField(max_length=20)),
                ('descripcion_falla', models.CharField(max_length=300, null=True)),
                ('descripcion_reparacion', models.CharField(max_length=300, null=True)),
                ('piezas_cambiadas', models.CharField(max_length=200, null=True)),
                ('nombre_receptor_de_trabajo', models.CharField(max_length=30)),
                ('run_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ascensores.cliente')),
            ],
        ),
    ]
